services:
  backend:
    container_name: "db2d-backend"
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    secrets:
      - postgres-password
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2d-postgres/db2d
      - SPRING_DATASOURCE_USERNAME=admin
    networks:
      - spring-postgres
  postgres:
    image: postgres
    container_name: "db2d-postgres"
    restart: always
    secrets:
      - postgres-password
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=db2d
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
      - PG_DATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
secrets:
  postgres-password:
    file: src/main/resources/db/postgres_password.txt
networks:
  spring-postgres:
    driver: bridge

volumes:
  postgres-volume: