spring:
  config:
    import: optional:configtree:/run/secrets/
  liquibase:
    change-log: classpath:db/db-changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/db2d
    username: admin
    password: ${postgres-password:12345}
  profiles:
    include: prod


