name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
    paths: ['server/**']
  pull_request:
    branches: [ "main" ]
    paths: ['server/**']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run the Maven verify phase
        run: |
          cd ./server/db2b
          mvn --batch-mode --update-snapshots verify